---
title: "iteration_and_listcols"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(rvest)
```


## Make a list

```{r}
l = 
  list(
    vec_numeric = 1:23,
    cha_vec = c("Jeff"),
    mat = matrix(1:8, nrow = 2, ncol = 4),
    summary = summary(rnorm(1000, mean = 4))
  )

l

l[[1]]
l[["vec_numeric"]]
```


## Make a different list

```{r}
list_normals <- 
  list(
    a = rnorm(30, mean = 3, sd = 1),
    b = rnorm(30, mean = 30, sd = 1),
    c = rnorm(30, mean = 3, sd = 10),
    d = rnorm(30, mean = -3, sd = 4)
  )
```


(copy and paste function from last time)

```{r}
mean_and_sd <- function(x) {
  
  
  if (!is.numeric(x)) {
    stop("The input x should be numeric.")
  }
  
  if (length(x) < 5) {
    stop("Only compute z scores when the input has 5 or more numbers.")
  }
  
  mean_x = mean(x, na.rm = TRUE)
  sd_x = sd(x, na.rm = TRUE)
  
  c(mean_x, sd_x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
  
}
```

```{r}
mean_and_sd(list_normals[[1]])
mean_and_sd(list_normals[[2]])
mean_and_sd(list_normals[[3]])
mean_and_sd(list_normals[[4]])
```

Use a loop to iterate!!

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_normals[[i]])
  
  
}

output
```


Use `map` to do the same thing.

```{r}
map(list_normals, mean_and_sd)
```

```{r}
map_dfr(list_normals, mean_and_sd, .id = "sample")

map_dbl(list_normals, median)
```


## List Columns

Try to put my list into a dataframe.

```{r}
listcol_df <- 
  tibble(
    name = c("a", "b", "c", "d"),
    sample = list_normals
  )
```

Did this really work??

```{r}
pull(listcol_df, sample)
```

Can I apply `mean_and_sd` ??

```{r}
mean_and_sd(
  pull(listcol_df, sample)[[1]]
)
```

iterate using `map`

```{r}
map(
  pull(listcol_df, sample), mean_and_sd
)
```

adding a column ... 

```{r}
listcol_df <- 
  listcol_df %>% 
  mutate(
    summary = map(sample, mean_and_sd)
  )
```


```{r}
listcol_df %>% 
  select(-sample) %>% 
  unnest(summary)
```


## Look at weather data

```{r}
library(p8105.datasets)
data("weather_df")
```

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

Let's do a regression!

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  lm(tmax ~ tmin, data = .)
```


Let's iterate differently...

```{r}
weather_nest <- 
  weather_df %>% 
  nest(data = date:tmin)
```


```{r}
lm(tmax ~ tmin, data = pull(weather_nest, data)[[1]])
```


Do this using `map`...

```{r}
weather_lm <- function(df) {
  
  lm(tmax ~ tmin, data = df)
  
  
}
```

```{r}
map(pull(weather_nest, data), weather_lm)
```

```{r}
weather_nest %>% 
  mutate(
    lm_fits = map(data, weather_lm)
  )
```

























