---
title: "simulation"
output: github_document
---


Loaad key packages and source neccesary files.
```{r}
library(tidyverse)
library(readxl)
library(rvest)

source("source/sim_mean_sd.R")
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

We can "simulate" by running our function... 

```{r}
sim_mean_sd(n_subj = 400)
```


Can I "verify" the CLT??

first with a `for` loop.

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(30)
  
}

output %>% 
  bind_rows() %>% 
  ggplot(aes(x = mu_hat)) +
  geom_density()
```

Try to repeat it with a map statement..

```{r}
sim_results_df <- 
  tibble(
    iter = 1:100
  ) %>% 
  mutate(
    results = map(iter, sim_mean_sd, n_subj = 30)
  ) %>% 
  unnest(results)
```

```{r}
sim_results_df <- 
  expand_grid(
    sample_size = c(30,60,90,120),
    iter = 1:1000
  ) %>% 
  mutate(
    results = map(sample_size, sim_mean_sd)
  ) %>% 
  unnest(results)
```


Let's look at this:

```{r}
sim_results_df %>% 
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mu_hat)) +
  geom_violin()
```

Let's try to summarize...

```{r}
sim_results_df %>% 
  group_by(sample_size) %>% 
  summarize(
    emp_mean = mean(mu_hat),
    emp_se = sd(mu_hat)
  )
```


## Simple linear regression

```{r}
sim_df <- 
  tibble(
    x = rnorm(n = 30, mean = 1, sd = 1),
    y = 2 + 3 * x + rnorm(30, 0, 1)
  )

sim_df %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point()

slr_fit <- lm(y ~ x, data = sim_df)

coef(slr_fit)
```


turn this into a function..!

```{r}
sim_regression <- function(n_subj, beta_0 = 2, beta_1 = 3) {
  
  sim_df = 
    tibble(
      x = rnorm(n_subj, mean = 1, sd = 1),
      y = beta_0 + beta_1 * x + rnorm(n_subj, 0, 1)
     )

  sim_df %>% 
    ggplot(aes(x = x, y = y)) +
    geom_point()

  slr_fit <- lm(y ~ x, data = sim_df)

  tibble(
    beta_0_hat = coef(slr_fit)[1],
    beta_1_hat = coef(slr_fit)[2]
  )
  
  
  
}
  
```


```{r}
sim_regression(n_subj = 30)
```

```{r}
output = vector("list", length = 500)

for (i in 1:500) {
  
  output[[i]] = sim_regression(n_subj = 30)
  
}

output %>% 
  bind_rows()
```










































