---
title: "writing_functions"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(rvest)
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



## Start small!!

Everyone loves z scores.

```{r}
x_vec <- rnorm(20, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Write a function to compute z scores.

```{r}
z_scores <- function(x) {
  
  if (!is.numeric(x)) {
    stop("The input x should be numeric.")
  }
  
  if (length(x) < 5) {
    stop("Only compute z scores when the input has 5 or more numbers.")
  }
  
  z = (x - mean(x)) / sd(x)
  
  z
}
```


Let's try our function....

```{r}
z_scores(x = x_vec)

num_vec <- rnorm(123, mean = 14, sd = 0.4)

z_scores(x = num_vec)
```


Let's break our function...

```{r, error=TRUE}
z_scores(3)
z_scores("my name is jeff")
```


## Let's compute some stuff....


```{r}
mean_and_sd <- function(x) {
  
  
  if (!is.numeric(x)) {
    stop("The input x should be numeric.")
  }
  
  if (length(x) < 5) {
    stop("Only compute z scores when the input has 5 or more numbers.")
  }
  
  mean_x = mean(x, na.rm = TRUE)
  sd_x = sd(x, na.rm = TRUE)
  
  c(mean_x, sd_x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
  
}

mean_and_sd(x = x_vec)

```

## Make up data..

Let's *simulate* some data..

```{r}
sim_df <- 
  tibble(
    x = rnorm(n = 30, mean = 3, sd = 2)
  )

sim_df %>% 
  summarize(
    mu_hat = mean(x),
    sigma_hat = sd(x)
  )
```

Write a function to do simulations.

We wrote it in a code chunk last time, now it is being sourced.

```{r}
source("source/sim_mean_sd.R")
```


Let's run this function.

```{r}
sim_mean_sd()
```


Import the LotR data.

```{r}
fellowship_ring <- 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "Fellowship of the Ring")

two_towers <- 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "Two Towers")

return_of_the_king <- 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "Return of the King")

lotr_df <- 
  bind_rows(fellowship_ring, two_towers, return_of_the_king)
```


Turn this into a function.

```{r}
lotr_import <- function(cell_range, movie_title) {
  
  df = read_excel("data/LotR_Words.xlsx", range = cell_range) %>% 
  mutate(movie = movie_title)
  
  df
  
}
```

```{r}
fellowship <- lotr_import(cell_range = "B3:D6", movie_title = "Fellowship")
two_towers <- lotr_import(cell_range = "F3:H6", movie_title = "Two Towers")
return_of_the_king <- lotr_import(cell_range = "J3:L6", movie_title = "Return of the King")

bind_rows(fellowship, two_towers, return_of_the_king)
```



























